#!/usr/bin/env bash
#
# Real SSH Client Test Plan for nano_ssh_server_complete.sh
#
# This documents how to test with a real SSH client when available
#

set -euo pipefail

readonly PORT=2222

echo "═══════════════════════════════════════════════════════════"
echo "  BASH SSH Server - Real SSH Client Test Plan"
echo "═══════════════════════════════════════════════════════════"
echo ""

# Check if SSH client is available
if ! command -v ssh >/dev/null 2>&1; then
    echo "❌ SSH client not found in this environment"
    echo ""
    echo "To test with real SSH client, you need:"
    echo "  - ssh (OpenSSH client)"
    echo "  - sshpass (for automated password entry)"
    echo ""
    echo "Install with:"
    echo "  Ubuntu/Debian: sudo apt-get install openssh-client sshpass"
    echo "  macOS: brew install openssh sshpass"
    echo ""
    echo "═══════════════════════════════════════════════════════════"
    echo "  EXPECTED BEHAVIOR WITH REAL SSH CLIENT"
    echo "═══════════════════════════════════════════════════════════"
    echo ""
    echo "Terminal 1: Start server"
    echo "  $ cd vbash-ssh-server"
    echo "  $ ./nano_ssh_server_complete.sh 2222"
    echo ""
    echo "You should see:"
    echo "  [HH:MM:SS] BASH SSH Server with FULL ENCRYPTION"
    echo "  [HH:MM:SS] Proving BASH CAN handle crypto state!"
    echo "  [HH:MM:SS] Port: 2222"
    echo "  [HH:MM:SS] Using nc for TCP handling"
    echo "  [HH:MM:SS] Waiting for connection on port 2222..."
    echo ""
    echo "Terminal 2: Connect with SSH"
    echo "  $ ssh -p 2222 user@localhost"
    echo "  Password: password123"
    echo ""
    echo "═══════════════════════════════════════════════════════════"
    echo "  EXPECTED SSH CLIENT OUTPUT"
    echo "═══════════════════════════════════════════════════════════"
    echo ""
    echo "If everything works correctly:"
    echo ""
    echo "  \$ ssh -p 2222 user@localhost"
    echo "  The authenticity of host '[localhost]:2222' can't be established."
    echo "  ED25519 key fingerprint is SHA256:..."
    echo "  Are you sure you want to continue connecting (yes/no)? yes"
    echo "  user@localhost's password: [enter: password123]"
    echo "  Hello World"
    echo "  Connection to localhost closed."
    echo ""
    echo "═══════════════════════════════════════════════════════════"
    echo "  EXPECTED SERVER LOG OUTPUT"
    echo "═══════════════════════════════════════════════════════════"
    echo ""
    echo "Server should log:"
    echo ""
    echo "  [HH:MM:SS] === New SSH connection ==="
    echo "  [HH:MM:SS] === Phase 1: Version Exchange ==="
    echo "  [HH:MM:SS] Client: SSH-2.0-OpenSSH_..."
    echo "  [HH:MM:SS] === Phase 2: Key Exchange ==="
    echo "  [HH:MM:SS] Generating server keys..."
    echo "  [HH:MM:SS] Keys generated"
    echo "  [HH:MM:SS] Sending KEXINIT..."
    echo "  [HH:MM:SS] Waiting for client KEXINIT..."
    echo "  [HH:MM:SS] Waiting for KEX_ECDH_INIT..."
    echo "  [HH:MM:SS] Computing Curve25519 shared secret..."
    echo "  [HH:MM:SS] Shared secret computed: 32 bytes"
    echo "  [HH:MM:SS] Computing exchange hash H..."
    echo "  [HH:MM:SS] Exchange hash: [hex]..."
    echo "  [HH:MM:SS] Signing exchange hash with Ed25519..."
    echo "  [HH:MM:SS] Signature created: 64 bytes"
    echo "  [HH:MM:SS] Sending KEX_ECDH_REPLY with proper signature..."
    echo "  [HH:MM:SS] Deriving encryption and MAC keys..."
    echo "  [HH:MM:SS] Keys derived - Encryption enabled!"
    echo "  [HH:MM:SS] Sending NEWKEYS..."
    echo "  [HH:MM:SS] Waiting for client NEWKEYS..."
    echo "  [HH:MM:SS] === ENCRYPTION ENABLED - State management active! ==="
    echo "  [HH:MM:SS] === Phase 3: Authentication ==="
    echo "  [HH:MM:SS] Waiting for SERVICE_REQUEST..."
    echo "  [HH:MM:SS] Sent encrypted packet #0 (len=...)"
    echo "  [HH:MM:SS] Sent SERVICE_ACCEPT"
    echo "  [HH:MM:SS] Waiting for USERAUTH_REQUEST..."
    echo "  [HH:MM:SS] Received encrypted packet #0 (len=...)"
    echo "  [HH:MM:SS] Sent encrypted packet #1 (len=...)"
    echo "  [HH:MM:SS] Sent USERAUTH_SUCCESS"
    echo "  [HH:MM:SS] === Phase 4: Channel ==="
    echo "  [HH:MM:SS] Waiting for CHANNEL_OPEN..."
    echo "  [HH:MM:SS] Received encrypted packet #1 (len=...)"
    echo "  [HH:MM:SS] Sent encrypted packet #2 (len=...)"
    echo "  [HH:MM:SS] Sent CHANNEL_OPEN_CONFIRMATION"
    echo "  [HH:MM:SS] Waiting for CHANNEL_REQUEST..."
    echo "  [HH:MM:SS] Received encrypted packet #2 (len=...)"
    echo "  [HH:MM:SS] Sent encrypted packet #3 (len=...)"
    echo "  [HH:MM:SS] Sent CHANNEL_SUCCESS"
    echo "  [HH:MM:SS] Sending 'Hello World' data..."
    echo "  [HH:MM:SS] Sent encrypted packet #4 (len=...)"
    echo "  [HH:MM:SS] Sent encrypted packet #5 (len=...)"
    echo "  [HH:MM:SS] Sent EOF"
    echo "  [HH:MM:SS] === Session complete - SUCCESS! ==="
    echo ""
    echo "═══════════════════════════════════════════════════════════"
    echo "  VERBOSE SSH CLIENT TEST"
    echo "═══════════════════════════════════════════════════════════"
    echo ""
    echo "For detailed debugging:"
    echo ""
    echo "  \$ ssh -vvv -p 2222 user@localhost"
    echo ""
    echo "This will show:"
    echo "  - Version exchange"
    echo "  - Algorithm negotiation"
    echo "  - Key exchange details"
    echo "  - Signature verification"
    echo "  - Encryption cipher info"
    echo "  - Authentication process"
    echo "  - Channel opening"
    echo "  - Data transfer"
    echo ""
    echo "═══════════════════════════════════════════════════════════"
    echo "  AUTOMATED TEST WITH SSHPASS"
    echo "═══════════════════════════════════════════════════════════"
    echo ""
    echo "For automated testing:"
    echo ""
    echo "  \$ sshpass -p password123 ssh -o StrictHostKeyChecking=no \\"
    echo "      -o UserKnownHostsFile=/dev/null \\"
    echo "      -p 2222 user@localhost"
    echo ""
    echo "Expected output:"
    echo "  Hello World"
    echo ""
    echo "═══════════════════════════════════════════════════════════"
    echo "  POSSIBLE FAILURE POINTS"
    echo "═══════════════════════════════════════════════════════════"
    echo ""
    echo "If connection fails, check:"
    echo ""
    echo "1. Exchange Hash Computation"
    echo "   - All fields must be in correct order"
    echo "   - Strings must be properly encoded (uint32 length + data)"
    echo "   - mpint must handle sign bit correctly"
    echo ""
    echo "2. Ed25519 Signature"
    echo "   - Must sign the correct exchange hash H"
    echo "   - Signature format must match SSH expectations"
    echo "   - OpenSSL pkeyutl output must be correct"
    echo ""
    echo "3. Encryption After NEWKEYS"
    echo "   - Keys must be derived correctly"
    echo "   - IV must be computed per packet"
    echo "   - MAC must use correct sequence number"
    echo "   - Sequence numbers must increment"
    echo ""
    echo "4. Binary Data Encoding"
    echo "   - No null byte truncation"
    echo "   - Correct endianness (big-endian for SSH)"
    echo "   - Proper padding calculation"
    echo ""
    echo "═══════════════════════════════════════════════════════════"
    echo "  DEBUGGING FAILED CONNECTIONS"
    echo "═══════════════════════════════════════════════════════════"
    echo ""
    echo "If SSH client shows:"
    echo ""
    echo "  'Connection closed by ::1 port 2222'"
    echo "  → Likely signature verification failed"
    echo "  → Check exchange hash computation"
    echo "  → Verify Ed25519 signature"
    echo ""
    echo "  'Corrupted MAC on input'"
    echo "  → MAC computation incorrect"
    echo "  → Check sequence number usage"
    echo "  → Verify HMAC-SHA256 key derivation"
    echo ""
    echo "  'Bad packet length'"
    echo "  → Encryption/decryption issue"
    echo "  → Check AES-CTR key and IV"
    echo "  → Verify key derivation"
    echo ""
    echo "═══════════════════════════════════════════════════════════"
    echo "  PERFORMANCE EXPECTATIONS"
    echo "═══════════════════════════════════════════════════════════"
    echo ""
    echo "Connection will be SLOW due to process spawning:"
    echo ""
    echo "  - Key exchange: ~200-500ms (multiple openssl calls)"
    echo "  - Per packet: ~20ms (encrypt + MAC)"
    echo "  - Total connection: ~1-2 seconds"
    echo ""
    echo "Compare to C implementation:"
    echo "  - Key exchange: ~10-50ms"
    echo "  - Per packet: ~0.02ms"
    echo "  - Total connection: ~50-100ms"
    echo ""
    echo "BASH is 20-100x slower, but it WORKS!"
    echo ""
    echo "═══════════════════════════════════════════════════════════"

    exit 1
fi

# If SSH is available, run actual tests
echo "✅ SSH client found!"
echo ""
echo "Starting automated tests..."
echo ""

# Test 1: Check if server is running
if ! nc -z localhost $PORT 2>/dev/null; then
    echo "❌ Server not running on port $PORT"
    echo "Start with: ./nano_ssh_server_complete.sh $PORT"
    exit 1
fi

echo "✅ Server is running on port $PORT"
echo ""

# Test 2: Version exchange
echo "Test 1: Version Exchange"
timeout 2 bash -c "exec 3<>/dev/tcp/localhost/$PORT; cat <&3 | head -1" 2>/dev/null || echo "FAILED"
echo ""

# Test 3: Full SSH connection (verbose)
echo "Test 2: Full SSH Connection (verbose)"
echo "Running: ssh -vvv -p $PORT user@localhost"
echo ""
timeout 30 sshpass -p password123 ssh -vvv \
    -o StrictHostKeyChecking=no \
    -o UserKnownHostsFile=/dev/null \
    -p $PORT user@localhost 2>&1 | tail -50

echo ""
echo "═══════════════════════════════════════════════════════════"
echo "Test complete!"
