#!/usr/bin/env python3
"""
Parse openssl RSA key output and convert to C array format
"""

import sys
import re

def parse_hex_section(text, start_marker):
    """Extract hex values from a section like 'modulus:' or 'privateExponent:'"""
    lines = text.split('\n')
    capturing = False
    hex_str = ""

    for line in lines:
        if start_marker in line:
            capturing = True
            continue
        if capturing:
            # Stop at next section or end
            if line and line[0] not in [' ', '\t']:
                break
            # Extract hex bytes (format: "    00:a7:3e:9d:...")
            hex_parts = re.findall(r'[0-9a-f]{2}', line)
            hex_str += "".join(hex_parts)

    return hex_str

def hex_to_c_array(hex_str, name):
    """Convert hex string to C array format"""
    bytes_list = [hex_str[i:i+2] for i in range(0, len(hex_str), 2)]

    print(f"/* {name} ({len(bytes_list)} bytes) */")
    print(f"static const uint8_t {name}[{len(bytes_list)}] = {{")

    for i in range(0, len(bytes_list), 8):
        chunk = bytes_list[i:i+8]
        line = "    " + ", ".join(f"0x{b}" for b in chunk)
        if i + 8 < len(bytes_list):
            line += ","
        print(line)

    print("};")
    print()

# Read openssl output
text = sys.stdin.read()

# Extract modulus and private exponent
modulus = parse_hex_section(text, "modulus:")
private_exp = parse_hex_section(text, "privateExponent:")

print("/* RSA-2048 Key Pair - Generated by openssl genrsa 2048 */")
print()

# Output C arrays
hex_to_c_array(modulus, "rsa_modulus")
hex_to_c_array(private_exp, "rsa_private_exponent")

print("/* Public exponent (e = 65537) */")
print("#define RSA_PUBLIC_EXPONENT 65537")
print()

print(f"/* Verification: Modulus is {len(modulus)//2} bytes, Private exponent is {len(private_exp)//2} bytes */")
